### ISSUE TITLE
Site não abre!

### ISSUE THREAD

**Issue by fgrehm** [joelbarbosa/coronavirus-brasil#1]
Bom dia @joelbarbosa!

Tentei acessar o http://coronavirusbrasil.org/index.html mas acho q o DNS não tá configurado?

**Comment by joelbarbosa** [comment]
Olá @fgrehm estou configurando o novo domínio, irei voltar até a alteração está pronta.
Obrigado.

**Comment by joelbarbosa** [comment]
https://joelbarbosa.github.io/coronavirus-brasil/
Funcionando.
